version: '3.4'
networks:
  QuizAppNetwork:
    driver: bridge
services:
  progquizwebsite:
    container_name: ProgQuizWebsiteContainer
    ports:
        - 1068:80
    networks:
        - QuizAppNetwork
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
        - PostgresDb
    
  PostgresDb:
        container_name: PostgresServerContainer
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Sonic.exe
            POSTGRES_DB: QuizDB
        ports:
            - 3666:5432
        networks:
            - QuizAppNetwork

