// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProgQuizWebsite.Infrastracture.Contexts;

#nullable disable

namespace ProgQuizWebsite.Migrations
{
    [DbContext(typeof(QuizAppContext))]
    [Migration("20240813170934_quiz ratings")]
    partial class quizratings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationUser", b =>
                {
                    b.Property<Guid>("NotificationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("NotificationUser");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Notifications.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.LanguageCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.QuizSubcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizContentModels.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizContentModels.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FailureInfo")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("SuccessInfo")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("LanguageCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCategoryId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.QuizRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizRatings");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Users.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Users.Models.UserModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizQuizSubcategory", b =>
                {
                    b.Property<Guid>("QuizzesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubcategoriesId")
                        .HasColumnType("uuid");

                    b.HasKey("QuizzesId", "SubcategoriesId");

                    b.HasIndex("SubcategoriesId");

                    b.ToTable("QuizQuizSubcategory");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("UserService.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NotificationUser", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Notifications.Models.Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgQuizWebsite.Domain.Users.Models.UserModel.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.QuizSubcategory", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.LanguageCategory", "LanguageCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("LanguageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageCategory");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizContentModels.Answer", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.QuizContentModels.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizContentModels.Question", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.Quiz", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.LanguageCategory", "LanguageCategory")
                        .WithMany("Quizzes")
                        .HasForeignKey("LanguageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.QuizRatingsInfo", "QuizRatingsInfo", b1 =>
                        {
                            b1.Property<Guid>("QuizId")
                                .HasColumnType("uuid");

                            b1.Property<int>("RatedByCount")
                                .HasColumnType("integer");

                            b1.Property<int>("RatingSum")
                                .HasColumnType("integer");

                            b1.HasKey("QuizId");

                            b1.ToTable("Quizzes");

                            b1.WithOwner()
                                .HasForeignKey("QuizId");
                        });

                    b.Navigation("LanguageCategory");

                    b.Navigation("QuizRatingsInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.QuizRating", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.Quiz", "Quiz")
                        .WithMany("QuizRatings")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgQuizWebsite.Domain.Users.Models.UserModel.User", "User")
                        .WithMany("QuizRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Users.Models.RefreshToken", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Users.Models.UserModel.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("ProgQuizWebsite.Domain.Users.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Users.Models.UserModel.User", b =>
                {
                    b.OwnsOne("ProgQuizWebsite.Domain.Users.Models.UserModel.UserInfo", "UserInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Login")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<long>("PhoneNumber")
                                .HasColumnType("bigint");

                            b1.Property<string>("Surname")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("ProgQuizWebsite.Domain.Users.Models.UserModel.UserNotificationsInfo", "UserNotificationsInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<int>("NewNotificationsCount")
                                .HasColumnType("integer");

                            b1.Property<bool>("ReceiveNotifications")
                                .HasColumnType("boolean");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("UserInfo")
                        .IsRequired();

                    b.Navigation("UserNotificationsInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("QuizQuizSubcategory", b =>
                {
                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.QuizSubcategory", null)
                        .WithMany()
                        .HasForeignKey("SubcategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("UserService.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgQuizWebsite.Domain.Users.Models.UserModel.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.CategoryModels.LanguageCategory", b =>
                {
                    b.Navigation("Quizzes");

                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizContentModels.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Quizzes.Models.QuizModels.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("QuizRatings");
                });

            modelBuilder.Entity("ProgQuizWebsite.Domain.Users.Models.UserModel.User", b =>
                {
                    b.Navigation("QuizRatings");

                    b.Navigation("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
